name: Test AI Inference

on:
  push:
    branches: [feature/-]
  pull_request:
    branches: [main, devlelop]
  workflow_dispatch:
    

jobs:
  inference:
    permissions:
      models: read
    runs-on: ubuntu-latest
    steps:
      - name: Test Local Action
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: "Hello, how are you?"
          model: "gpt-4o"
          endpoint: "https://api.rdsec.trendmicro.com/prod/aiendpoint/v1/"
          token: ${{ secrets.TM_API_KEY }}
          max-tokens: 1000

      - name: Print Output
        id: output
        run: echo "${{ steps.inference.outputs.response }}"

      - name: Fetch Issue
        id: issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            })
            core.setOutput('title', issue.data.title)
            core.setOutput('body', issue.data.body)
            
    

      
